services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel12_api_admin_docker_app
        volumes:
            - .:/var/www/html
        env_file: .env
        depends_on:
            - mysql_db
            - pg_db

    nginx:
        image: nginx:alpine
        container_name: laravel12_api_admin_docker_app_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    mysql_db:
        image: mysql:8.0
        container_name: laravel12_api_admin_docker_app_docker_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./docker/mysql_data:/var/lib/mysql

    pg_db:
        image: postgres:15-alpine
        container_name: laravel12_api_admin_docker_postgres
        environment:
            POSTGRES_DB: ${PG_DB_NAME}
            POSTGRES_USER: ${PG_DB_USER}
            POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
        volumes:
            - ./docker/pg_data:/var/lib/postgresql/data

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel12_api_admin_docker_phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: ${DB_HOST}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql_db

    redis:
        image: redis:alpine
        container_name: laravel12_api_admin_docker_redis

    memcached:
        image: memcached:alpine
        container_name: laravel12_api_admin_docker_memcached
